### ISSUE TITLE
urllib3 not installed by default on ubuntu 16.04 amazon images

### ISSUE THREAD

**Issue by avinson** [foxpass/foxpass-setup#10]
foxpass_setup.py fails to run without a `pip install urllib3` on ubuntu 16.04 and this is not mentioned in the docs.

**Comment by avinson** [comment]
can we have a bash option for this again? it seems like a better choice due to portability issues, imho.

**Comment by aren** [comment]
Where do you host your machines and what image do you use? AWS's 16.04 comes with urllib3.

Based on the script's complexity we're trying to stick with python. Perhaps a re-write without urllib3 will make it possible.

**Comment by avinson** [comment]
I was able to confirm that urllib3 is installed by default on latest official ubuntu 16.04 AMI. I must be doing something with my config that is causing the issue. Sorry for the false alarm.
