### ISSUE TITLE
foxpass setup script can sometimes fail if apt lock is in place

### ISSUE THREAD

**Issue by avinson** [foxpass/foxpass-setup#13]
this is more of an fyi thing than a real bug.. because i have a system image with security autoupdates enabled, it will do an apt-get update at first boot. since foxpass-setup also does this, sometimes it will fail with:
```
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
```
i've added a simple loop to my userdata script as a fix but you may consider incorporating some similar logic into foxpass-setup:
```
# wait for other apt processes to finish before running foxpass script
while fuser /var/lib/dpkg/lock; do
   sleep 1
done
```

**Comment by aren** [comment]
Thanks for the report. You may also wish to run foxpass-setup once, and then bake the image. Then it won't conflict with your on-boot updater.

**Comment by avinson** [comment]
@aren good suggestion.. the reason why i am doing things this way is that terraform has some nice vault integration that i can use to parameterize any secrets.. that way my images have no secret data until they're launched
