### ISSUE TITLE
foxpass_setup.py: generate incorrect /usr/local/sbin/foxpass_ssh_keys.sh

### ISSUE THREAD

**Issue by ArtemChekunov** [foxpass/foxpass-setup#56]
in python `backslash` `\` is a special character aka escape symbol
when python writes a file with the `backslash` the next symbol will be escaped

which mean `\\` **=>** `\`

```
Python 3.9.12 (main, Mar 26 2022, 15:52:10)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.31.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: f = open('a_file', "w")

In [2]: f.write('foo\\bar')
Out[2]: 7

In [3]: f.close()

In [4]: cat a_file
foo\bar
```

so `if grep -q "^${user/./\\.}:" /etc/passwd; then exit; fi` turns to `if grep -q "^${user/./\.}:" /etc/passwd; then exit; fi`

This means if a user has a dot in the name for example `foo.bar` it's not gonna be escaped on the bash side.

**test:**
```
cat > passwd_test <<EOF
foo.bar:pwd
foo bar:pwd
foo_bar:pwd
foo-bar:pwd
foo2bar:pwd
EOF

user='foo.bar'
grep "^${user/./\.}:" passwd_test
foo.bar:pwd
foo bar:pwd
foo_bar:pwd
foo-bar:pwd
foo2bar:pwd

grep "^${user/./\\.}:" passwd_test
foo.bar:pwd
```

**Comment by ArtemChekunov** [comment]
I create a [PR ](https://github.com/foxpass/foxpass-setup/pull/57)

**Comment by asakapab0i** [comment]
PR merged.
