### ISSUE TITLE
Ubuntu 14.04 Install script fails with syntax errors

### ISSUE THREAD

**Issue by jgoldsmi** [foxpass/foxpass-setup#6]
The Ubuntu 14.04 install shell script doesn't work, failing with syntax errors.

In Ubuntu/Debian, `/bin/sh` is typically the [dash shell](https://en.wikipedia.org/wiki/Almquist_shell), which means syntax like
```shell
function cache_up_to_date() {
```
won't work, as well as the `local` keyword.

Also here: https://github.com/foxpass/foxpass-setup/blob/master/linux/ubuntu/14.04/foxpass_setup.sh#L47, the variables aren't prefixed with `$`, so the shell will try and execute them as commands.

**Comment by aren** [comment]
We have deprecated the shell scripts in favor of the python one (you'll find it in the same directory). Please let me know how you fare with those. Thanks!

**Comment by jgoldsmi** [comment]
Deprecating them is fine, but you guys updated and broke them. Would you consider reverting the latest commit on these files back to when they worked and maybe print some kind of deprecation warning when you run them so people know that you'd like them to switch to the python version?

**Comment by aren** [comment]
Great point. We'll look into what's going on, and add a deprecation notice.

**Comment by aren** [comment]
Shell script has been fixed; I am not sure what shell that was for but it wasn't dash. I am sorry that made it into our repo and caused you grief.

https://github.com/foxpass/foxpass-setup/commit/bc598d350ffb9619606b85cb3d510a70039d60c5

Per your suggestion, a deprecation warning was added.
