### ISSUE TITLE
AWS IMDSv2 Compatibility

### ISSUE THREAD

**Issue by tony-highspot** [foxpass/foxpass-setup#62]
Many of the scripts in this repo are not compatible with [AWS IMDSv2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html). This includes the Ubuntu 21.04 and Ubuntu 22.04 scripts.

If you search, you will find many instances of code like the following

```sh
aws_instance_id=`curl -s -q -f http://169.254.169.254/latest/meta-data/instance-id`
aws_region_id=`curl -s -q -f http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/.$//'`

```
I suggest replacing the above code with the following code across the repo:

```sh
aws_meta_data_token=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 60")
aws_instance_id=$(curl -s -q -f -H "X-aws-ec2-metadata-token: $aws_meta_data_token" http://169.254.169.254/latest/meta-data/instance-id)
aws_region_id=$(curl -s -q -f -H "X-aws-ec2-metadata-token: $aws_meta_data_token" http://169.254.169.254/latest/meta-data/placement/region')
```

Note, shellcheck recommended the use of `$(...)` over backticks `` `...` ``

**Comment by aren** [comment]
Hi Tony -- we recently merged in a PR to address this. https://github.com/foxpass/foxpass-setup/pull/54

Have you tried with the newest version of the scripts?

**Comment by aren** [comment]
@asakapab0i consider using the `$(...)` instead of backticks.

**Comment by tony-highspot** [comment]
Seems like those changes didn't make it into 

https://github.com/foxpass/foxpass-setup/blob/master/linux/ubuntu/22.04/foxpass_setup.py#L120

or 

https://github.com/foxpass/foxpass-setup/blob/master/linux/ubuntu/21.04/foxpass_setup.py#L120

I guessing those were added later.

**Comment by asakapab0i** [comment]
Noted @aren ,

As for the 22.04 and 21.04 versions, the IMDSv2 support is added to this PR.

https://github.com/foxpass/foxpass-setup/pull/61

https://github.com/foxpass/foxpass-setup/blob/b95ef4976f355449f889d4909dc05cbb852a0143/linux/ubuntu/21.04/foxpass_setup.py
https://github.com/foxpass/foxpass-setup/blob/b95ef4976f355449f889d4909dc05cbb852a0143/linux/ubuntu/22.04/foxpass_setup.py

**Comment by tony-highspot** [comment]
Nice, thank you!

**Comment by aren** [comment]
@tony-highspot can you check the scripts in this PR?

https://github.com/foxpass/foxpass-setup/pull/63

**Comment by tony-highspot** [comment]
Hello @aren, I have reviewed the shell script code in question and found that it appears to be correct and functional. If you would like, I can provide suggestions for cosmetic and maintainability improvements. Here are my recommendations:

Firstly, I suggest replacing the backticks with the `$()` syntax for command substitution. This is considered a more modern and readable syntax.

Secondly, I recommend changing the last metadata call to use the http://169.254.169.254/latest/meta-data/placement/region endpoint instead of using the availability zone endpoint followed by `sed`. This will simplify the code.

Lastly, I suggest using the long form of arguments in scripts rather than the short form (`-s` and `-q`). This will make the code more readable, especially if a lot of common arguments are used. Additionally, you can pack them into a variable to further simplify the code.

Overall, these changes will improve the code's readability and maintainability.

```sh
common_curl_args="--silent --disable --fail"
aws_meta_data_token=$(curl $common_curl_args --request PUT "http://169.254.169.254/latest/api/token" --header "X-aws-ec2-metadata-token-ttl-seconds: 60")
aws_instance_id=$(curl $common_curl_args -H "X-aws-ec2-metadata-token: $aws_meta_data_token" "http://169.254.169.254/latest/meta-data/instance-id")
aws_region_id=$(curl $common_curl_args --header "X-aws-ec2-metadata-token: $aws_meta_data_token" "http://169.254.169.254/latest/meta-data/placement/region")
```

**Comment by aren** [comment]
Glad to see they finally have a `region` endpoint! They didn't used to.

@asakapab0i can you please incorporate @tony-highspot's feedback for this PR?

**Comment by tony-highspot** [comment]
Yup, its relatively new: was released 2020-08-24. I remember asking someone at Amazon why it didn't exist and the response was something along the lines of "just use sed or something" ^_^
